apiVersion: v1
kind: Service
metadata:
  namespace: greeting #-api
  name: greeting #-service  
  labels:
    app: greeting  
spec:
  selector:
    app: greeting #-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
#  type: NodePort
#  type: LoadBalancer