apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: httpbin
spec:
  selector:
    app: httpbin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
#  type: NodePort
#  type: LoadBalancer